# Generated by Django 4.2 on 2023-06-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_link",
            field=models.CharField(
                default="https://insomniac.games/wp-content/uploads/2018/09/Spider-Man_PS4_Selfie_Photo_Mode_LEGAL.jpg",
                max_length=1000,
            ),
        ),
    ]
