# Generated by Django 4.2 on 2023-06-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_post_image_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="mins",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AddField(
            model_name="post",
            name="rating",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AddField(
            model_name="post",
            name="year",
            field=models.CharField(default="", max_length=4),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_link",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
