# Generated by Django 4.2 on 2023-06-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_post_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="bg_img",
            field=models.ImageField(blank=True, default="", upload_to="images"),
        ),
        migrations.AlterField(
            model_name="post",
            name="cover",
            field=models.ImageField(blank=True, default="", upload_to="images"),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_link",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="post",
            name="mins",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="post",
            name="rating",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="year",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
    ]
