# Generated by Django 4.2 on 2023-06-17 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_post_bg_img_alter_post_cover_alter_post_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="image_link",
            new_name="video_link",
        ),
    ]
