# Generated by Django 4.2 on 2023-06-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rename_image_link_post_video_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="genere",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
