# Generated by Django 4.2 on 2023-06-21 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_post_date_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date_time",
            new_name="date",
        ),
    ]
